services:

  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redispassword --appendonly yes

  service_manager:
    build:
      context: ./service_manager
    image: dheerajkumarp/fleet_service_manager:latest
    container_name: service_manager
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8100
    environment:
      - DATABASE_URL=postgresql://maintainer:password@gocab.tech:5432/fleet
      - OAUTH2_ENV=dev
      - OAUTH2_URL=http://localhost:8100/api/auth/introspect
      - REDIS_HOST=redis_server
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=redispassword
      - USE_REDIS=1
      - TOKEN_EXPIRY_HOURS=1
      - X_INTROSPECT_SECRET=Kjs#idjXw
    depends_on:
      - redis_server
    ports:
      - "8100:8100"
    # remove this volume in production unless you want live code overrides
    # volumes:
    #   - ./service_manager:/app

volumes:
  redis_data:
